name: edman_web Unittest

on:
  push:
    branches: [ develop ]

jobs:
  edman_unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '7.0' ]

    steps:
      # Equivalent to 'actions/checkout@v6.0.2'
      - name: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Equivalent to 'actions/setup-python@v6.2.0'
      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
          check-latest: true
      - run: python -m venv venv
      - run:  source ./venv/bin/activate
      - run:  pip install -U pip setuptools
      - run:  pip install sphinx pytest mypy flake8
      - run:  pip install -r ./requirements.txt
      - run:  cp ./tests/ini/test_db.ini.sample ./tests/ini/test_db.ini

      # Equivalent to 'actions/setup-python@1.12.1'
      - name: setup DB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: admin
          mongodb-password: admin
          mongodb-db: admin

      - name: run pytest
        run: |
          cd ./tests
          pytest

      - name: run mypy
        run: |
          mypy ./edman_web

      - name: run flake8
        run: |
          flake8 ./edman_web

      - name: API doc output and push gh-pages
        run: |
          mkdir ./api_docs
          sphinx-apidoc -F -o ./api_docs ./edman_web/
      - run: |
          cd ./api_docs
          make html
      # Equivalent to 'upload-pages-artifact@v5'
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ./api_docs/_build/html

  deploy:
    needs: edman_unittest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Equivalent to 'actions/deploy-pages@v5'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128

